$if (CFIBPROMPTS_INC)
$else
const CFIBPROMPTS_INC  = "Included";
const CFIB_HELLO_IB    = CFIB_PROMPTS & "hello.ul";
const CFIB_GOODBYE     = CFIB_PROMPTS & "goodbye.ul";
const CFIB_RECEND      = CFIB_PROMPTS & "recend.ul";
const CFIB_HELLO_OB    = CFIB_PROMPTS & "hello.ul";
const CFIB_ACCEPT_OB   = CFIB_PROMPTS & "accept.ul";
const CFIB_ACCEPT_IB   = CFIB_PROMPTS & "acceptib.ul";
const CFIB_CALLINIT    = CFIB_PROMPTS & "callinit.ul";
const CFIB_ENTERPIN    = CFIB_PROMPTS & "entpin.ul";
const CFIB_CEENTPIN    = CFIB_PROMPTS & "ceentpin.ul";
const CFIB_ENTERNUM    = CFIB_PROMPTS & "entnum.ul";
const CFIB_HOLD        = CFIB_PROMPTS & "holdon.ul";
const CFIB_STARTTALK   = CFIB_PROMPTS & "statalk.ul";
const CFIB_REJECTED    = CFIB_PROMPTS & "rejected.ul";
const CFIB_CEHUP          = CFIB_PROMPTS & "cehup.ul";
const CFIB_TERMERR        = CFIB_PROMPTS & "termerr.ul";
const CFIB_INVALIDPIN     = CFIB_PROMPTS & "invalidpin.ul";
const CFIB_REENTERPIN     = CFIB_PROMPTS & "reenterpin.ul";
const CFIB_INACTIVEPIN    = CFIB_PROMPTS & "inactivepin.ul";
const CFIB_INVALIDRESP    = CFIB_PROMPTS & "invalidresp.ul"; 
const CFIB_MAXCALLS       = CFIB_PROMPTS & "maxcalls.ul";
const CFIB_NOPAIR_SBJ     = CFIB_PROMPTS & "nopair_sbj.ul";
const CFIB_WRONGPHONE     = CFIB_PROMPTS & "wrongphone.ul";
const CFIB_FORASSIST      = CFIB_PROMPTS & "forassist.ul";
const CFIB_NUMVAL         = CFIB_PROMPTS & "numval.ul";
const CFIB_TODIS          = CFIB_PROMPTS & "todis.ul";
const CFIB_EXTRAINFO      = CFIB_PROMPTS & "extrainfo.ul"; 
const CFIB_SURVEYQA       = CFIB_PROMPTS & "surveyqa.ul"; 
const CFIB_SURVEYQB       = CFIB_PROMPTS & "surveyqb.ul"; 
const CFIB_SURVEYRA       = CFIB_PROMPTS & "surveyra.ul"; 
const CFIB_SURVEYRB       = CFIB_PROMPTS & "surveyrb.ul"; 
const CFIB_COMMENT        = CFIB_PROMPTS & "comment.ul"; 
const CFIB_THANKYOU       = CFIB_PROMPTS & "thankyou.ul"; 
const CFIB_PINREQ         = CFIB_PROMPTS & "pinreq.ul"; 
const CFIB_PINREQ_NAME    = CFIB_PROMPTS & "prname.ul"; 
const CFIB_PINREQ_PHNUM   = CFIB_PROMPTS & "prphnum.ul"; 
const CFIB_PINREQ_GEND    = CFIB_PROMPTS & "prgend.ul"; 
const CFIB_PINREQ_SUCCESS = CFIB_PROMPTS & "prsucc.ul"; 
const CFIB_PINREQ_REPEAT  = CFIB_PROMPTS & "prrpt.ul";   
const CFIB_PINREQ_FAIL    = CFIB_PROMPTS & "prfail.ul"; 
const CFIB_PINQRY         = CFIB_PROMPTS & "pinquery.ul"; 
const CFIB_PINCONFIRM     = CFIB_PROMPTS & "pinconfirm.ul"; 
const CFIB_NCZERO         = CFIB_PROMPTS & "NC0000ENG.ul";
const CFIB_NCONE          = CFIB_PROMPTS & "NC0001ENG.ul";
const CFIB_NCTWO          = CFIB_PROMPTS & "NC0002ENG.ul";
const CFIB_NCTHREE        = CFIB_PROMPTS & "NC0003ENG.ul";
const CFIB_NCFOUR         = CFIB_PROMPTS & "NC0004ENG.ul";
const CFIB_NCFIVE         = CFIB_PROMPTS & "NC0005ENG.ul";
const CFIB_NCSIX          = CFIB_PROMPTS & "NC0006ENG.ul";
const CFIB_NCSEVEN        = CFIB_PROMPTS & "NC0007ENG.ul";
const CFIB_NCEIGHT        = CFIB_PROMPTS & "NC0008ENG.ul";
const CFIB_NCNINE         = CFIB_PROMPTS & "NC0009ENG.ul";

$endif


