$if (CFIBPROMPTS_INC)
$else
const CFIBPROMPTS_INC  = "Included";
const CFIB_HELLO_IB    = CFIB_PROMPTS & "hello.ul";
const CFIB_GOODBYE     = CFIB_PROMPTS & "goodbye.ul";
const CFIB_RECEND      = CFIB_PROMPTS & "recend.ul";
const CFIB_HELLO_OB    = CFIB_PROMPTS & "hello.ul";
const CFIB_ACCEPT_OB   = CFIB_PROMPTS & "accept.ul";
const CFIB_ENTERPIN    = CFIB_PROMPTS & "entpin.ul";
const CFIB_ENTERNUM    = CFIB_PROMPTS & "entnum.ul";
const CFIB_HOLD        = CFIB_PROMPTS & "holdon.ul";
const CFIB_STARTTALK   = CFIB_PROMPTS & "statalk.ul";
const CFIB_REJECTED    = CFIB_PROMPTS & "rejected.ul";
const CFIB_CEHUP       = CFIB_PROMPTS & "cehup.ul";
const CFIB_TERMERR     = CFIB_PROMPTS & "termerr.ul";
const CFIB_INVALIDPIN  = CFIB_PROMPTS & "invalidpin.ul";
const CFIB_REENTERPIN  = CFIB_PROMPTS & "reenterpin.ul";
const CFIB_INACTIVEPIN = CFIB_PROMPTS & "inactivepin.ul";
const CFIB_MAXCALLS    = CFIB_PROMPTS & "maxcalls.ul";
const CFIB_NOPAIR_SBJ  = CFIB_PROMPTS & "nopair_sbj.ul";
const CFIB_WRONGPHONE  = CFIB_PROMPTS & "wrongphone.ul";
const CFIB_FORASSIST   = CFIB_PROMPTS & "forassist.ul";
const CFIB_NUMVAL      = CFIB_PROMPTS & "numval.ul";
const CFIB_TODIS       = CFIB_PROMPTS & "todis.ul";
const CFIB_EXTRAINFO   = CFIB_PROMPTS & "extrainfo.ul"; 
const CFIB_SURVEYQA    = CFIB_PROMPTS & "surveyqa.ul"; 
const CFIB_SURVEYQB    = CFIB_PROMPTS & "surveyqb.ul"; 
const CFIB_SURVEYRA    = CFIB_PROMPTS & "surveyra.ul"; 
const CFIB_SURVEYRB    = CFIB_PROMPTS & "surveyrb.ul"; 
const CFIB_COMMENT     = CFIB_PROMPTS & "cfibcomment.ul"; 
const CFIB_THANKYOU    = CFIB_PROMPTS & "cfibthankyou.ul"; 

$endif


