
$if (PROMPTS_INC)
$else

const PROMPTS_INC  = "Included";

const ENG          = "ENG";
const SPA          = "SPA";
const TON          = "TON";

const EN_NAMES     = FSH_BASE    & "partnames\";
const EN_TOPICS    = FSH_PROMPTS & "Topics\";
const SP_NAMES     = FSH_BASE    & "partnames\";
const NAMEPRPT     = FSH_BASE    & "partnames\";
const SP_TOPICS    = FSH_PROMPTS & "Topics\";

const TONE         = FSH_PROMPTS & "tone.ul";
const FSH_MOH1     = FSH_PROMPTS & "moh1.ul";
const FSH_MOH2     = FSH_PROMPTS & "moh2.ul";
const FSH_MOH3     = FSH_PROMPTS & "moh3.ul";
const FSH_MOHN     = FSH_PROMPTS & "mohn.ul";

const HELLO_IB     = 1;
const GOODBYE      = 2;
const HELLO_OB     = 3;
const THANKYOU     = 4;
const ACCEPT_OB    = 5;
const ENTERPIN     = 6;
const HOLD         = 7;
const HOLD2        = 8;
const CONTINUE     = 9;
const WELCOME      = 10;
const RECSTART     = 11;
const TOPICDAY     = 12;
const WARN1        = 13;
const WARN2        = 14;
const TIMESUP      = 15;
const PARTTHANK    = 16;
const INVALID      = 17;
const ENTERPIN2    = 18;
const HOLDEXIT     = 19;
const RECEND       = 26;
const RECNOW       = 25;
const INTRODUCE    = 27;
const URONHOLD     = 28;
const LEAVECOMM    = 29;
const CMOVER       = 30;
const TOTOVER      = 31;
const NACTIVE      = 32;
const TDYMOVER     = 33;
const TDYROVER     = 34;
const ANIMOVER     = 35;
const FORASST      = 36;
const RECANNC      = 37;
const PHNTYPE      = 38;
const PHNSET       = 39;
const PROBLEM      = 40;
const DBERR        = 41;
const FSINTRO      = 42;
const FSRECNOW     = 43;
const NUMVAL       = 48;
const RECORDNAME   = 50;
const STATENAME	   = 51;
const RECDNAME	   = 52;
const RECORDOKYN   = 53;
const LNGDAYREJ	   = 54;
const RECMSG       = 55;

$endif


