
$if (PERLDEF_INC)
$else

const PERLDEF_INC = "Included";
const FSH_CLEARCIP        = FSH_PERL_EXE & "clrcip.pl";
const FSH_GETCALLEE       = FSH_PERL_EXE & "getcallee.pl";
const FSH_GETPINFNAME     = FSH_PERL_EXE & "getpinfname.pl";
const FSH_GETTOD          = FSH_PERL_EXE & "gettod.pl";
const MX3_GETTOD          = FSH_PERL_EXE & "gettod.pl";
const FSHSPA_LOGBRIDGE    = FSH_PERL_EXE & "logbridge.pl";
const FSHENG_LOGBRIDGE    = FSH_PERL_EXE & "logbridge.pl";
const MX3_LOGBRIDGE       = FSH_PERL_EXE & "logbridge.pl";
const FSHSPA_LOGTERM      = FSH_PERL_EXE & "logterm.pl";
const FSHENG_LOGTERM      = FSH_PERL_EXE & "logterm.pl";
const FSH_LOGTERM         = FSH_PERL_EXE & "logterm.pl";
const MX3_LOGTERM         = FSH_PERL_EXE & "logterm.pl";
const FSHSPA_LOGVAL       = FSH_PERL_EXE & "logval.pl";
const FSHENG_LOGVAL       = FSH_PERL_EXE & "logval.pl";
const MX3_LOGVAL          = FSH_PERL_EXE & "logval.pl";
const FSHSPA_NEWSIDE      = FSH_PERL_EXE & "newside.pl";
const FSHENG_NEWSIDE      = FSH_PERL_EXE & "newside.pl";
const MX3_NEWSIDE         = FSH_PERL_EXE & "newside.pl";
const FSH_VALIDPIN        = FSH_PERL_EXE & "validpin.pl";
const MX3_VALIDPIN        = FSH_PERL_EXE & "validpin.pl";
const MX3_UDCMADE         = FSH_PERL_EXE & "udcmade.pl";

$endif

