
$if (CFIBDEF_INC)
$else

const CFIBDEF_INC 	   = "Included";
const CFIB_VALIDPIN        = CFIB_PERL_EXE & "validpin.pl";
const CFIB_NEWSIDE         = CFIB_PERL_EXE & "newside.pl";
const CFIB_LOGBRIDGE       = CFIB_PERL_EXE & "logbridge.pl";
const CFIB_LOGTERM         = CFIB_PERL_EXE & "logterm.pl";
const CFIB_CLRPROC         = CFIB_PERL_EXE & "clrproc.pl";
const CFIB_DELPROC         = CFIB_PERL_EXE & "delproc.pl";
const CFIB_LOGVAL          = CFIB_PERL_EXE & "logval.pl";
const CFIB_LOGSURVEY       = CFIB_PERL_EXE & "logsurvey.pl";

$endif

