
$if (RPT_FIELDS_INC)
$else

const CALL_ID      = 1;     
const FILA         = 2;
const FILB         = 3;
const FILESIZA     = 4;
const FILESIZB     = 5;
const SUBJ_ID      = 6;
const CE_SUBJ_ID   = 7;
const CRA_SUBJID   = 8;
const CRB_SUBJID   = 9;
const TIMESTAMP    = 10;
const PIN          = 11;
const NUMBER       = 12;
const PAIR         = 13;
const PAIRNUMBER   = 14;
const MYPHNSET     = 15;
const PAIRPHNSET   = 16;
const MYPHNTYPE    = 17;
const PAIRPHNTYPE  = 18;
const TOPIC        = 19;
const TOPIC_ID     = 20;
const RECORDING    = 21;
const RUNTIME      = 22;
const POSANSR 	   = 23;
const POSPIN 	   = 24;
const HUPB4BRIDGE  = 25;
const SHORTREC     = 26;
const FULLREC 	   = 27;
const EMPTYKUE     = 28;
const POSOFFHOOK   = 29;
const SUCCESS      = 30;
const NOREC        = 31;
const TOPREJECT    = 32;
const TOHTIME      = 33;
const CRA_SIDEID   = 34;
const CRB_SIDEID   = 35;
const TERMSTAT     = 36;

$endif;